import React from 'react';
import type { Metadata } from 'next';

import './globals.css';
import { geistMono } from './assets/fonts/fonts';

import MainHeader from '@/components/MainHeader/MainHeader';
import AppSidebar from '@/components/AppSidebar/AppSidebar';
import Providers from './providers';

export const metadata: Metadata = {
  title: 'Devko',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={` ${geistMono.variable} antialiased`}>
        <Providers>
          <MainHeader />
          <div className='flex min-h-screen'>
            <AppSidebar />
            <main className='flex w-full flex-1 flex-col items-center px-2 pl-16 pt-20'>
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
