import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import MainHeader from '@/components/MainHeader/MainHeader';
import Providers from './providers';
import AppSidebar from '@/components/AppSidebar/AppSidebar';
import React from 'react';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Devko',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainHeader />
        <Providers attribute='class' defaultTheme='system' enableSystem>
          <div className='flex min-h-screen'>
            <AppSidebar />
            <div className='flex flex-1 flex-col items-center'>
              <main className='w-full px-2 pl-16 pt-20'>{children}</main>
              {/* <main className='flex-1 overflow-auto p-4'>{children}</main> */}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
